version: '3'
services:
  awesome-women:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - node_modules:/app/awesome-women/node_modules
    stdin_open: true
    tty: true

volumes:
  .:
    driver: local
  node_modules: